### PR TITLE
First pass at adding Serilog.

### PR DESCRIPTION
**Pull request by aaronmell**
Ready for code review.

### CODE REVIEW

**Comment by sbohlen** [comment]
First, thanks for the PR; the work is much appreciated!

Second, sorry for the delay in my reviewing this; between traveling last week and a dust-up at work, I've been slammed the past bit.  Fortunately I was able to pull together some time last evening to review this more fully and some time this morning to compose a more comprehensive response.

After taking a look @ the implementation, I do have a few questions/comments, some of which may well simply be the result of my lack of familiarity with `Serilog` (as mentioned, I've not used `Serilog` in the past and so can't speak from experience re: how it works).

After reading the code (including the initial unit test -- thanks for those, BTW!) and tracing through the test-run in the debugger a few times, I think I'm still a bit confused as to your approach.  It almost seems as if rather than this being an adapter for `Common.Logging` users to leverage `Serilog`, its instead more of a way for `Serilog` users to plug `Serilog` into `Common.Logging`.  I'm not sure I'm understanding this properly; can you help me better understand your general intent with this?

Your [integration test](https://github.com/aaronmell/common-logging/blob/bafac2cfa08cd3fe91a71ff5174702dbd6d1cf00/test/Common.Logging.Serilog1514.Integration.Tests/Logging/Serilog/CommonLoggingSerilogTests.cs) first news up the `Common.Logging` adapter and sets its factory as would be expected of an integration test, but then the test code switches to interacting directly with `Serilog` types (e.g., `Serilog.LoggerConfiguration`, `Serilog.ILogger`) to configure and retrieve a logger instance with which to then write log entries.  

`Common.Logging` typically expects the `Common.Logging.ILoggerFactoryAdapter` implementation to be responsible for reading configuration and retrieving an instance of the logger as a `Common.Logging.ILog` instance that the user then interacts with to commit log entries.  Instead, your implementation seems to have the user call `Serilog` directly and then `Serilog` sends log output to the `CommonLoggingSink` that then leverages your implementation of the `Common.Logging.ILoggerFactoryAdapter` to pass `Serilog` log entries through to any _other_ `Common.Logging` logger that might be configured.

Can you help me understand whether the usage pattern I see in the test is a convenience for the sake of easily setting up the test case, or is it indicative of how a user would be expected to interact with your implementation more generally?  My rough interpretation of the overall approach you've used here is that it seems to me that it would require a user to code against `Serilog` directly, and then `Serilog` would use the `CommonLoggingSink` to pass events through to some _other_ logger also configured as `Common.Logging`.

This impression is reinforced to me by the [app.config file](https://github.com/aaronmell/common-logging/blob/bafac2cfa08cd3fe91a71ff5174702dbd6d1cf00/test/Common.Logging.Serilog1514.Integration.Tests/App.config) you've created for the integration test that seems to contain configuration metadata that`Serilog` expects rather than metadata that `Common.Logging` would expect as was used in e.g., [this test](https://github.com/net-commons/common-logging/blob/master/test/Common.Logging.MultipleLogger.Tests/App.config).  Its also pointed to by your [`CommonLoggingSink` code](https://github.com/aaronmell/common-logging/blob/bafac2cfa08cd3fe91a71ff5174702dbd6d1cf00/src/Common.Logging.Serilog1514/Logging/Serilog/CommonLoggingSink.cs#L69) that checks for and rejects `Common.Logging` having been configured with your `Serilog`-specific factory adapter (for the mentioned reason that it would result in endless recursion).

I'd expected the `Serilog` implementation to align more closely with the approaches used for other `Common.Logging` adapters where the `LogManager.Adapter` property would be set to an instance of the `SerilogLoggerFactoryAdapter` that would then be responsible for the configuration and construction of the logger when the user calls `LogManager.GetLogger<T>(...)` to return a `Common.Logging.ILog` instance with which to interact.  Interacting with that `Common.Logging.ILog` instance would then redirect logging activities to the underlying `Serilog` instance.

Some of my confusion also comes from my observation that you _do_ seem to use this expected pattern in your [other test](https://github.com/aaronmell/common-logging/blob/bafac2cfa08cd3fe91a71ff5174702dbd6d1cf00/test/Common.Logging.Serilog1514.Tests/Logger/Serilog/SerilogTests.cs).  But the way I understand your implementation of the `CommonLoggingSink` class, attempting to actually log anything using the `Common.Logging.ILog` instance returned by that call to `LogManager.GetLogger<T>(...)` would be expected to throw because the configured factory in that test is the `SerilogLoggerFactoryAdapter` type that your sink disallows in order to avoid infinite recursion.

As mentioned, its entirely possible that I'm just too much of a `Serilog` noob to properly understand how you've approached this; can you help improve my understanding of the points I've identified above?

**Comment by aaronmell** [comment]
The integration test was based on this one for [Nlog](https://github.com/aaronmell/common-logging/blob/bafac2cfa08cd3fe91a71ff5174702dbd6d1cf00/test/Common.Logging.NLog10.Tests/Logger/NLog/CommonLoggingTargetTests.cs) And based on the behavior of nlog to be able to configure send messages to common.logging. Since Serilog supports that same type of behavior via Sinks, I went ahead and implemented the pattern to do so. 

The other test was based on the tests for **[ENTLib](https://github.com/net-commons/common-logging/blob/f9964f86f5ae409af62f26d599db555e04884f59/test/Common.Logging.EntLib31.Tests/Logging/EntLib/EntLibTests.cs) Maybe those tests were not the best to model my tests after, and they are pretty basic. If you think I need some additional tests here, I can write some. 

If you look at my [SerilogLoggerFactoryAdapter.cs](https://github.com/aaronmell/common-logging/blob/bafac2cfa08cd3fe91a71ff5174702dbd6d1cf00/src/Common.Logging.Serilog1514/Logging/Serilog/SerilogLoggerFactoryAdapter.cs)  It creates a new instance of Serilogger.

And the [Serlogger.cs](https://github.com/aaronmell/common-logging/blob/bafac2cfa08cd3fe91a71ff5174702dbd6d1cf00/src/Common.Logging.Serilog1514/Logging/Serilog/SerilogLogger.cs) takes that instance and pushes logs to serilogger.

My intented behavior was for it to work like other logging adapters, you use the adapter for serilog in common logging and messages are routed to serilog.

**Comment by sbohlen** [comment]
Ah, interesting ... so these two tests actually represent two _different_ use-cases/usage patterns for Serilog support: one that relies upon the behavior in the `CommonLoggingSink` and another that's designed to work more "traditionally".  I'd not considered that; now I get it :)

I'll take another look again this evening and provide some more detailed feedback in light of this explanation; thanks again for the initial PR!

**Comment by sbohlen** [comment]
Thanks for the contribution; I've merged the PR into MASTER.  I have a few tweaks I need to make to your implementation, but nothing major -- primarily I want to move the Serilog-specific changes you introduced in `AbstractLogger` back into your `SerilogLogger` subclass, but otherwise this looks like a really solid contribution -- thanks again for both the work and your patience as I took a bit longer to review this than I'd originally hoped.

**Pull request merged**
