### PR TITLE
replaced NLog 4.1.0 with 4.1.2

### PR DESCRIPTION
**Pull request by 304NotModified**
fixes https://github.com/net-commons/common-logging/issues/102

nlog 4.0,  4.1.1, 4.1.2,  4.2.0,  4.2.1 etc has same assembly version

### CODE REVIEW

**Comment by 304NotModified** [comment]
@sbohlen can this be merged and released?

**Comment by sbohlen** [comment]
Yeah, I'd hoped/planned to do it this past weekend but was unable to do so.

I'm traveling today but should be able to process this tomorrow when I return.

Sorry for the delay in this (and a few other  recent issues); for the past few weeks I've been dealing with a health issue in my immediate family (resolved just this past weekend -- fortunately favorably) and its created some chaos for the rest of my life :P

-Steve B.

-----Original Message-----

**Comment by 304NotModified** [comment]
OK thx

**Comment by 304NotModified** [comment]
@sbohlen bump.

**Comment by 304NotModified** [comment]
Thanks for the deployment @sbohlen

**Pull request merged**
