### PR TITLE
Added support for NLog and Log4Net GlobalContext and ThreadContext

### PR DESCRIPTION
**Pull request by meixger**
Added support for NLog and Log4Net GlobalContext and ThreadContext via new Properties on ILog and a new interface IVariablesContext.
Added tests, all existing and new tests pass.

Note: This is only a cleaned version of @DannyVarod pull request https://github.com/net-commons/common-logging/pull/50

### CODE REVIEW

**Comment by sbohlen** [comment]
@meixger:

Since you originally authored this feature, would you be willing to weight-in on issue https://github.com/net-commons/common-logging/issues/81 for us?  Although I'm not likely to have a chance to look into this in more detail until the coming weekend, I'm curious your thoughts on it...is this perhaps an overlooked edge-case that isn't (yet) supported as I surmise in my reply to  the OP?

Thanks!

**Comment by DannyVarod** [comment]
Hi Steve,

Sure, done - I think the issue is in Log4Net, however, I would like the OP
to test to confirm this.

By the way, there are a couple of new features I need, however, these are
not deal breaker as the context feature was and I currently have a large
workload currently, so it may take me time to get to implementing them:

1. Enable passing MethodInfo of calling method to NLog/Log4Net so when
logging via an Aspect, correct location/callsite gets logged.
2. Enable logging with log level as parameter, so if log level is
configurable, using code will not have to use switch/case.

Example of usage:
https://pubcomp.codeplex.com/SourceControl/latest#Aspects/Monitoring/LogAttribute.cs

Regards,
Danny.

**Comment by sbohlen** [comment]
@DannyVarod 

Thanks for chiming in on this -- sorry I missed crediting yourself as the original contributor; when I went looking back through the closed PRs I found this one from @meixger mis-recalled him as the originator of this feature b/c I didn't bother to read the rest of this thread :)

I suspect as you do that this is a limitation of Log4Net rather than a problem with the GlobalContext support in Common.Logging per se, but I figured I'd give you a chance to offer input if poss. since I can't likely get to this myself until the weekend.

re: the other two features you mention, I totally grok the need for 1. to address the use-case you suggest where Common.Logging would be otherwise unable to properly reverse-engineer the 'intended' callsite on its own without some assistance in the form of a param that indicates the 'logical' callsite intended vs. the 'actual' one Common.Logging would improperly infer.  Unfortunately this probably also will require a change to the `ILog` interface to accommodate it and so we're likely staring at _another_ breaking change coming here :(

However, I'm curious re: whether 2. really represents a sufficiently-common use-case to warrant a change to Common.Logging to support it.  I completely see from your example how your aspect in this situation needs to contain the switch/case statement to address its specific needs in re: its interaction with Common.Logging, but I'm curious whether this is really a general use-case or merely an edge case.  TBH, I've not seen this pattern for consuming Common.Logging in more general use 'in the wild' (usually calling code 'knows' whether it means to log e.g., a DEBUG vs. INFO message and so no switch/case construct is necessary).

That said, since we'd have to introduce a breaking change to support 1., I suppose there's no harm in having a second breaking change to support your 2. while we're at it :)  I've opened two new issues (https://github.com/net-commons/common-logging/issues/82 & https://github.com/net-commons/common-logging/issues/83) to track these ideas.

Thanks again for your continued contributions (and participating in the community!)

**Comment by DannyVarod** [comment]
Hi Steve,

I'm currently using this to handle trace logging and exception logging in
the new services developed within my employing company, some of which have
already become productional.

Regarding the configurable level, as some exceptions can be expected e.g.
concurrency exceptions, which are handled and retried, a log severity of
error would cause unnecessary production alerts. Log level of trace vs
debug, for different depths of the service enables changing the verbosity
of the logs i.e. external calls only, or also inner trace.

Regarding usage via aspects, it enables logging exceptions, calls to the
service, duration of high complexity method, all with a 3 attributes per
assembly. I am only directly calling the log methods on service start and
on expected exceptions e.g. call to external service fails, item not found
in DB, however, not for other cases e.g. DB connection fails.

Other aspects I am using include setting a correlation ID on thread context
on each service call, enabling correlating the logs per call, retry
operations on specific exceptions, caching results of specific operations.
I have made some of these available in my open source project.

I am happy to give back to the community, there is no point on continuing
to develop basic stuff over and over again.

Regards,
Danny.

**Pull request merged**
