### PR TITLE
Add Xamarin and WinStore/Phone support with PCL Profile 259 (.NET 4.5)

### PR DESCRIPTION
**Pull request by anjdreas**
Adds .NET 4.5 portable profile 259.
This profile is widely used and well supported by Xamarin for iOS and Android, as well as all the Windows targets for PC and mobile.

Target: portable-net45+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1

The biggest challenge was fixing all the reflection code to support the new reflection API around [TypeInfo](http://blogs.msdn.com/b/dotnet/archive/2012/08/28/evolving-the-reflection-api.aspx). This API is not supported in the current portable profile 136 for .NET 4.0, since it is only available in .NET 4.5 and later.

Portable nuget now has the following targets: .NET 3.5, .NET 4.0 (pcl) and .NET 4.5 (pcl)

Some cleanup:
* Rename PORTABLE compile condition to PORTABLE40, and add PORTABLE45
* Rename portable projects to Common.Logging.Portable.2010-netxx for consistency
* Change output paths to /build/portable/
* Use separate intermediate output paths for portable projects to avoid "already in use" build errors in Visual Studio

I particularly want review on the following changes:
* [Remove net40 target in nuget](https://github.com/anjdreas/common-logging/commit/a15d76afcbff8b724682536befd8682fb3046241)
* [Updating CommonAssemblyInfo](https://github.com/anjdreas/common-logging/commit/fcdf78ba5fbeab8a1cf30ef5dfc94e19dcc9d22d)
* [Returning "N/A" for thread ID in ExceptionFormatter.cs](https://github.com/anjdreas/common-logging/commit/31247394b81969d47b96cd0f2e31820378585670)
* [Translations of reflection code to new reflection API](https://github.com/anjdreas/common-logging/commit/31247394b81969d47b96cd0f2e31820378585670)
* [Delete seemingly unused portable project](https://github.com/anjdreas/common-logging/commit/6adda64a0f45fef73dbf130c3ad4d8ed220c2559)

### CODE REVIEW

**Comment by sbohlen** [comment]
Thanks for the comments/PR.  From my read of this, you have come up against the blocker outlined here https://github.com/net-commons/common-logging/issues/71.  Your proposed solution in re: "Common.Logging.Interfaces" sounds (nearly) identical to the outlined changes in Common.Logging.Core in that issue/thread, so I'm presuming that this set of changes in the PCL-EXPERIMENTATION branch (https://github.com/net-commons/common-logging/tree/pcl-experimentation) is likely to address your blockers as well (?)

Can you comment on this --?

**Comment by anjdreas** [comment]
Sorry, I've written my own log interface and adapter since then. It was just easier in the end. [PortableLog](https://github.com/anjdreas/portablelog). I have shamelessly copied quite a bit of the common-logging code, but added my own flavor to it. I hope you don't mind. You can close this pull request if you want.

**Comment by sbohlen** [comment]
I don't mind at all; sorry you weren't able to wait for us to get the PCL story properly sorted on our end.

Cheers,

-Steve B.

**Comment by anjdreas** [comment]
Thanks, cheers!

**Pull request closed without merging**
