### PR TITLE
Issue 128 - Support for Nested Contexts

### PR DESCRIPTION
**Pull request by Moily**
Added INestedVariablesContext / NestedVariablesContext to ILog. 
Working implementations for log4net and NLog.

### CODE REVIEW

**Comment by sbohlen** [comment]
Merged; thanks for the (revised) PR and all your efforts on this!

**Comment by Moily** [comment]
Thanks for accepting the functionality!

On a not-entirely-unrelated note, do you have an estimated date when the next version will be released to nuget?

**Comment by sbohlen** [comment]
I'll package this up as a BETA-1 (pre-release) for NuGet later this morning.

The final 3.4-GA  is now only waiting on our solidifying a coherent story around the configuration experience in our DNX/.NET Core support.  Once that's done, we will probably do a BETA-2 with the .NET Core config story in it so that we can get some feedback on the approach we select.  If there are any issues raised in BETA-2, then we'll address them and then do an RC release.  If there aren't any issues raised in BETA-2, we might just go straight to 3.4-GA from the BETA-2.

All told, my hope is that we can have a 3.4-GA release ready by EOM (October) with some luck on our side.

**Comment by Moily** [comment]
Great, looking forward to it!

**Comment by Moily** [comment]
Hi Steve,

Any updates on when you think 3.4 can be released?  It seems to have gone very quiet since October.

Regards

**Pull request merged**
